### ISSUE TITLE
Setting docker & node-express server

### ISSUE THREAD

**Issue by devJang** [Yomni/hagseon_web#4]

**Comment by Yomni** [comment]
complete develop server setting & auto deploy

**Comment by devJang** [comment]
issue close하는 법 참고

http://sunghwanjo.tistory.com/entry/Github%EC%97%90%EC%84%9C-Commit-%EB%A9%94%EC%84%B8%EC%A7%80%EB%A5%BC-%ED%95%A0%EC%9A%A9%ED%95%B4%EC%84%9C-issues-%EC%83%81%ED%83%9C-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0-Closing-issues-via-commit-messages
